services:
  # Backend API Service
  - type: web
    name: rag-web-svc-backend
    env: python
    plan: free
    branch: master
    buildCommand: "python -m pip install --upgrade pip && python -m pip install -r requirements_minimal.txt"
    startCommand: "python -m uvicorn enhanced_rag_chatbot:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: OPENAI_API_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        value: "https://humanist96.github.io,https://rag-web-svc-frontend.onrender.com"
      - key: RENDER
        value: "true"
  
  # Frontend Static Site
  - type: static
    name: rag-web-svc-frontend
    plan: free
    branch: master
    buildCommand: "echo 'No build required for static files'"
    staticPublishPath: ./
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=3600
    routes:
      - type: rewrite
        source: /
        destination: /premium_index.html