services:
  - type: web
    name: rag-web-svc-backend
    env: python
    plan: free
    branch: master
    buildCommand: "python -m pip install --upgrade pip && python -m pip install -r requirements_minimal.txt"
    startCommand: "python -m uvicorn enhanced_rag_chatbot:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: OPENAI_API_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        value: "https://humanist96.github.io"
      - key: RENDER
        value: "true"